///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SwissCom
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The loginRemedy recording.
    /// </summary>
    [TestModule("0e273086-b799-46aa-90de-3fa42480d643", ModuleType.Recording, 1)]
    public partial class LoginRemedy : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SwissComRepo repository.
        /// </summary>
        public static SwissComRepo repo = SwissComRepo.Instance;

        static LoginRemedy instance = new LoginRemedy();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginRemedy()
        {
            Browser = "Chrome";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginRemedy Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Browser.
        /// </summary>
        [TestVariable("c5e1d94e-b770-4a19-ad85-fade486ffa66")]
        public string Browser
        {
            get { return repo.Browser; }
            set { repo.Browser = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://desktop-c80mesn/arsys/forms/desktop-c80mesn/HPD%3AHelp+Desk/Best+Practice+View/?cacheid=14a7d99b' with browser specified by variable $Browser in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://desktop-c80mesn/arsys/forms/desktop-c80mesn/HPD%3AHelp+Desk/Best+Practice+View/?cacheid=14a7d99b", Browser, "", false, true, false, false, false, true);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginPage.txt_userName' at Center.", repo.LoginPage.txt_userNameInfo, new RecordItemIndex(2));
            repo.LoginPage.txt_userName.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tosho' with focus on 'LoginPage.txt_userName'.", repo.LoginPage.txt_userNameInfo, new RecordItemIndex(3));
            repo.LoginPage.txt_userName.PressKeys("tosho");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginPage.txt_password' at Center.", repo.LoginPage.txt_passwordInfo, new RecordItemIndex(4));
            repo.LoginPage.txt_password.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'LoginPage.txt_password'.", repo.LoginPage.txt_passwordInfo, new RecordItemIndex(5));
            repo.LoginPage.txt_password.PressKeys("1");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'LoginPage.txt_password'.", repo.LoginPage.txt_passwordInfo, new RecordItemIndex(6));
            repo.LoginPage.txt_password.PressKeys("{Return}");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(7));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(8));
            Keyboard.Press("{Return}");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'LoginPage.btn_logIn'.", repo.LoginPage.btn_logInInfo, new RecordItemIndex(9));
            Validate.NotExists(repo.LoginPage.btn_logInInfo);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
