///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SwissCom
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SwissComRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("05f39afb-bbd5-40dd-b9b1-a986a7574ee7")]
    public partial class SwissComRepo : RepoGenBaseFolder
    {
        static SwissComRepo instance = new SwissComRepo();
        SwissComRepoFolders.HPD_AssociationsFolder _hpd_associations;
        SwissComRepoFolders.IncidentRelationshipSearchFolder _incidentrelationshipsearch;
        SwissComRepoFolders.IncidentModificationFolder _incidentmodification;
        SwissComRepoFolders.LoginPageFolder _loginpage;
        SwissComRepoFolders.IncidentFormFolder _incidentform;
        SwissComRepoFolders.BMCRemedySearchAppFolder _bmcremedysearch;
        SwissComRepoFolders.NewTabAppFolder _newtab;
        SwissComRepoFolders.MozillaFirefoxAppFolder _mozillafirefox;
        SwissComRepoFolders.TortoiseGitAppFolder _tortoisegit;
        SwissComRepoFolders.ChromeAppFolder _chrome;

        /// <summary>
        /// Gets the singleton class instance representing the SwissComRepo element repository.
        /// </summary>
        [RepositoryFolder("05f39afb-bbd5-40dd-b9b1-a986a7574ee7")]
        public static SwissComRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SwissComRepo() 
            : base("SwissComRepo", "/", null, 0, false, "05f39afb-bbd5-40dd-b9b1-a986a7574ee7", ".\\RepositoryImages\\SwissComRepo05f39afb.rximgres")
        {
            _hpd_associations = new SwissComRepoFolders.HPD_AssociationsFolder(this);
            _incidentrelationshipsearch = new SwissComRepoFolders.IncidentRelationshipSearchFolder(this);
            _incidentmodification = new SwissComRepoFolders.IncidentModificationFolder(this);
            _loginpage = new SwissComRepoFolders.LoginPageFolder(this);
            _incidentform = new SwissComRepoFolders.IncidentFormFolder(this);
            _bmcremedysearch = new SwissComRepoFolders.BMCRemedySearchAppFolder(this);
            _newtab = new SwissComRepoFolders.NewTabAppFolder(this);
            _mozillafirefox = new SwissComRepoFolders.MozillaFirefoxAppFolder(this);
            _tortoisegit = new SwissComRepoFolders.TortoiseGitAppFolder(this);
            _chrome = new SwissComRepoFolders.ChromeAppFolder(this);
        }

#region Variables

        string _INC_ID = "INC000000000068";

        /// <summary>
        /// Gets or sets the value of variable INC_ID.
        /// </summary>
        [TestVariable("7340b87e-ddd2-4e26-8e16-58c025df1443")]
        public string INC_ID
        {
            get { return _INC_ID; }
            set { _INC_ID = value; }
        }

        string _Browser = "Chrome";

        /// <summary>
        /// Gets or sets the value of variable Browser.
        /// </summary>
        [TestVariable("8bf349d7-8f9e-42bf-8b67-6f4964d51fe9")]
        public string Browser
        {
            get { return _Browser; }
            set { _Browser = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("05f39afb-bbd5-40dd-b9b1-a986a7574ee7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The HPD_Associations folder.
        /// </summary>
        [RepositoryFolder("7958c6e3-32db-40b1-a3e2-163b55a83dc5")]
        public virtual SwissComRepoFolders.HPD_AssociationsFolder HPD_Associations
        {
            get { return _hpd_associations; }
        }

        /// <summary>
        /// The IncidentRelationshipSearch folder.
        /// </summary>
        [RepositoryFolder("cc39b646-3c9d-434b-a9a3-43f6f23ddc11")]
        public virtual SwissComRepoFolders.IncidentRelationshipSearchFolder IncidentRelationshipSearch
        {
            get { return _incidentrelationshipsearch; }
        }

        /// <summary>
        /// The IncidentModification folder.
        /// </summary>
        [RepositoryFolder("25ff2b1a-1f63-42a2-8fb4-b7e1f3766cac")]
        public virtual SwissComRepoFolders.IncidentModificationFolder IncidentModification
        {
            get { return _incidentmodification; }
        }

        /// <summary>
        /// The LoginPage folder.
        /// </summary>
        [RepositoryFolder("1d913ee0-31e4-4f30-b25f-ba0bce4d67c6")]
        public virtual SwissComRepoFolders.LoginPageFolder LoginPage
        {
            get { return _loginpage; }
        }

        /// <summary>
        /// The IncidentForm folder.
        /// </summary>
        [RepositoryFolder("8902fdd3-5533-41a7-a25e-4265827b540b")]
        public virtual SwissComRepoFolders.IncidentFormFolder IncidentForm
        {
            get { return _incidentform; }
        }

        /// <summary>
        /// The BMCRemedySearch folder.
        /// </summary>
        [RepositoryFolder("eba120b7-e883-4be3-9c39-73117f3175ef")]
        public virtual SwissComRepoFolders.BMCRemedySearchAppFolder BMCRemedySearch
        {
            get { return _bmcremedysearch; }
        }

        /// <summary>
        /// The NewTab folder.
        /// </summary>
        [RepositoryFolder("eb9433e0-0c90-4072-b5d2-7e4fb48a66f2")]
        public virtual SwissComRepoFolders.NewTabAppFolder NewTab
        {
            get { return _newtab; }
        }

        /// <summary>
        /// The MozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("ca272b25-723b-4dd5-bf12-f017431bba8c")]
        public virtual SwissComRepoFolders.MozillaFirefoxAppFolder MozillaFirefox
        {
            get { return _mozillafirefox; }
        }

        /// <summary>
        /// The TortoiseGit folder.
        /// </summary>
        [RepositoryFolder("c2973527-fabb-450d-9376-707097ab30d5")]
        public virtual SwissComRepoFolders.TortoiseGitAppFolder TortoiseGit
        {
            get { return _tortoisegit; }
        }

        /// <summary>
        /// The Chrome folder.
        /// </summary>
        [RepositoryFolder("c1343d9b-4edd-4c9b-b7cb-b3ed53e09c71")]
        public virtual SwissComRepoFolders.ChromeAppFolder Chrome
        {
            get { return _chrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SwissComRepoFolders
    {
        /// <summary>
        /// The HPD_AssociationsFolder folder.
        /// </summary>
        [RepositoryFolder("7958c6e3-32db-40b1-a3e2-163b55a83dc5")]
        public partial class HPD_AssociationsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txt_entry2_requestidInfo;
            RepoItemInfo _txt_entry1_requestidInfo;
            RepoItemInfo _mn_associationtypeInfo;

            /// <summary>
            /// Creates a new HPD_Associations  folder.
            /// </summary>
            public HPD_AssociationsFolder(RepoGenBaseFolder parentFolder) :
                    base("HPD_Associations", "/dom[@domain='desktop-c80mesn']", parentFolder, 30000, null, false, "7958c6e3-32db-40b1-a3e2-163b55a83dc5", "")
            {
                _txt_entry2_requestidInfo = new RepoItemInfo(this, "txt_Entry2_RequestID", ".//textarea[@id<'1000000205']", 30000, null, "1a5bb701-8846-4811-89a4-a4cab51a122f");
                _txt_entry1_requestidInfo = new RepoItemInfo(this, "txt_Entry1_RequestID", ".//textarea[@id<'1000000204']", 30000, null, "3cfdb065-79e2-4525-834c-fc48785d3725");
                _mn_associationtypeInfo = new RepoItemInfo(this, "mn_AssociationType", ".//input[@id<'1000000208']", 30000, null, "94bd13d7-eb86-4b97-8eb1-cc48b36a2194");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7958c6e3-32db-40b1-a3e2-163b55a83dc5")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7958c6e3-32db-40b1-a3e2-163b55a83dc5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txt_Entry2_RequestID item.
            /// </summary>
            [RepositoryItem("1a5bb701-8846-4811-89a4-a4cab51a122f")]
            public virtual Ranorex.TextAreaTag txt_Entry2_RequestID
            {
                get
                {
                    return _txt_entry2_requestidInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The txt_Entry2_RequestID item info.
            /// </summary>
            [RepositoryItemInfo("1a5bb701-8846-4811-89a4-a4cab51a122f")]
            public virtual RepoItemInfo txt_Entry2_RequestIDInfo
            {
                get
                {
                    return _txt_entry2_requestidInfo;
                }
            }

            /// <summary>
            /// The txt_Entry1_RequestID item.
            /// </summary>
            [RepositoryItem("3cfdb065-79e2-4525-834c-fc48785d3725")]
            public virtual Ranorex.TextAreaTag txt_Entry1_RequestID
            {
                get
                {
                    return _txt_entry1_requestidInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The txt_Entry1_RequestID item info.
            /// </summary>
            [RepositoryItemInfo("3cfdb065-79e2-4525-834c-fc48785d3725")]
            public virtual RepoItemInfo txt_Entry1_RequestIDInfo
            {
                get
                {
                    return _txt_entry1_requestidInfo;
                }
            }

            /// <summary>
            /// The mn_AssociationType item.
            /// </summary>
            [RepositoryItem("94bd13d7-eb86-4b97-8eb1-cc48b36a2194")]
            public virtual Ranorex.InputTag mn_AssociationType
            {
                get
                {
                    return _mn_associationtypeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The mn_AssociationType item info.
            /// </summary>
            [RepositoryItemInfo("94bd13d7-eb86-4b97-8eb1-cc48b36a2194")]
            public virtual RepoItemInfo mn_AssociationTypeInfo
            {
                get
                {
                    return _mn_associationtypeInfo;
                }
            }
        }

        /// <summary>
        /// The IncidentRelationshipSearchFolder folder.
        /// </summary>
        [RepositoryFolder("cc39b646-3c9d-434b-a9a3-43f6f23ddc11")]
        public partial class IncidentRelationshipSearchFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txt_incidentrelationship_searchvalueInfo;
            RepoItemInfo _txt_incidentrelationship_incidentidInfo;
            RepoItemInfo _btn_useadvancedsearchInfo;

            /// <summary>
            /// Creates a new IncidentRelationshipSearch  folder.
            /// </summary>
            public IncidentRelationshipSearchFolder(RepoGenBaseFolder parentFolder) :
                    base("IncidentRelationshipSearch", "/dom[@domain='desktop-c80mesn' and @caption='Incident Relationship Search']", parentFolder, 30000, null, false, "cc39b646-3c9d-434b-a9a3-43f6f23ddc11", "")
            {
                _txt_incidentrelationship_searchvalueInfo = new RepoItemInfo(this, "txt_IncidentRelationship_searchValue", ".//div[@class='btntextdiv']//div[@innertext='Search']", 30000, null, "fc88c520-6caa-4e0b-b94f-90c65e0c0c5c");
                _txt_incidentrelationship_incidentidInfo = new RepoItemInfo(this, "txt_IncidentRelationship_IncidentID", ".//div[@arid='1000000161']/textarea[@tagname='textarea']", 30000, null, "d0f142f5-ba2b-47dd-a16f-7a7e126b25fb");
                _btn_useadvancedsearchInfo = new RepoItemInfo(this, "btn_useAdvancedSearch", ".//div[@innertext='Use Advanced Search']", 30000, null, "abc759c4-8afe-422f-903b-0b47fbd929bf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cc39b646-3c9d-434b-a9a3-43f6f23ddc11")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cc39b646-3c9d-434b-a9a3-43f6f23ddc11")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txt_IncidentRelationship_searchValue item.
            /// </summary>
            [RepositoryItem("fc88c520-6caa-4e0b-b94f-90c65e0c0c5c")]
            public virtual Ranorex.DivTag txt_IncidentRelationship_searchValue
            {
                get
                {
                    return _txt_incidentrelationship_searchvalueInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The txt_IncidentRelationship_searchValue item info.
            /// </summary>
            [RepositoryItemInfo("fc88c520-6caa-4e0b-b94f-90c65e0c0c5c")]
            public virtual RepoItemInfo txt_IncidentRelationship_searchValueInfo
            {
                get
                {
                    return _txt_incidentrelationship_searchvalueInfo;
                }
            }

            /// <summary>
            /// The txt_IncidentRelationship_IncidentID item.
            /// </summary>
            [RepositoryItem("d0f142f5-ba2b-47dd-a16f-7a7e126b25fb")]
            public virtual Ranorex.TextAreaTag txt_IncidentRelationship_IncidentID
            {
                get
                {
                    return _txt_incidentrelationship_incidentidInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The txt_IncidentRelationship_IncidentID item info.
            /// </summary>
            [RepositoryItemInfo("d0f142f5-ba2b-47dd-a16f-7a7e126b25fb")]
            public virtual RepoItemInfo txt_IncidentRelationship_IncidentIDInfo
            {
                get
                {
                    return _txt_incidentrelationship_incidentidInfo;
                }
            }

            /// <summary>
            /// The btn_useAdvancedSearch item.
            /// </summary>
            [RepositoryItem("abc759c4-8afe-422f-903b-0b47fbd929bf")]
            public virtual Ranorex.DivTag btn_useAdvancedSearch
            {
                get
                {
                    return _btn_useadvancedsearchInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The btn_useAdvancedSearch item info.
            /// </summary>
            [RepositoryItemInfo("abc759c4-8afe-422f-903b-0b47fbd929bf")]
            public virtual RepoItemInfo btn_useAdvancedSearchInfo
            {
                get
                {
                    return _btn_useadvancedsearchInfo;
                }
            }
        }

        /// <summary>
        /// The IncidentModificationFolder folder.
        /// </summary>
        [RepositoryFolder("25ff2b1a-1f63-42a2-8fb4-b7e1f3766cac")]
        public partial class IncidentModificationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txt_resolutionInfo;

            /// <summary>
            /// Creates a new IncidentModification  folder.
            /// </summary>
            public IncidentModificationFolder(RepoGenBaseFolder parentFolder) :
                    base("IncidentModification", "/dom[@domain='desktop-c80mesn' and @browser='{Form:Incident Modification - Google Chrome}']", parentFolder, 30000, null, false, "25ff2b1a-1f63-42a2-8fb4-b7e1f3766cac", "")
            {
                _txt_resolutionInfo = new RepoItemInfo(this, "txt_Resolution", ".//div[@arid='1000000156']//textarea", 30000, null, "206f81af-eb2c-40eb-99b9-38216bf61a55");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("25ff2b1a-1f63-42a2-8fb4-b7e1f3766cac")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("25ff2b1a-1f63-42a2-8fb4-b7e1f3766cac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txt_Resolution item.
            /// </summary>
            [RepositoryItem("206f81af-eb2c-40eb-99b9-38216bf61a55")]
            public virtual Ranorex.TextAreaTag txt_Resolution
            {
                get
                {
                    return _txt_resolutionInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The txt_Resolution item info.
            /// </summary>
            [RepositoryItemInfo("206f81af-eb2c-40eb-99b9-38216bf61a55")]
            public virtual RepoItemInfo txt_ResolutionInfo
            {
                get
                {
                    return _txt_resolutionInfo;
                }
            }
        }

        /// <summary>
        /// The LoginPageFolder folder.
        /// </summary>
        [RepositoryFolder("1d913ee0-31e4-4f30-b25f-ba0bce4d67c6")]
        public partial class LoginPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txt_usernameInfo;
            RepoItemInfo _txt_passwordInfo;
            RepoItemInfo _btn_loginInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "/dom[@path>'/arsys/shared/login.jsp']", parentFolder, 5000, null, false, "1d913ee0-31e4-4f30-b25f-ba0bce4d67c6", "")
            {
                _txt_usernameInfo = new RepoItemInfo(this, "txt_userName", ".//input[#'username-id']", 30000, null, "66be8023-f5f7-4d13-98c3-32598a7659e7");
                _txt_passwordInfo = new RepoItemInfo(this, "txt_password", ".//input[#'pwd-id']", 30000, null, "119b93b8-c90c-4a9d-8550-844404d7a985");
                _btn_loginInfo = new RepoItemInfo(this, "btn_logIn", ".//input[#'login']", 1, null, "723c0aae-fee4-4a46-8d2f-8157392b719b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1d913ee0-31e4-4f30-b25f-ba0bce4d67c6")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1d913ee0-31e4-4f30-b25f-ba0bce4d67c6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txt_userName item.
            /// </summary>
            [RepositoryItem("66be8023-f5f7-4d13-98c3-32598a7659e7")]
            public virtual Ranorex.InputTag txt_userName
            {
                get
                {
                    return _txt_usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_userName item info.
            /// </summary>
            [RepositoryItemInfo("66be8023-f5f7-4d13-98c3-32598a7659e7")]
            public virtual RepoItemInfo txt_userNameInfo
            {
                get
                {
                    return _txt_usernameInfo;
                }
            }

            /// <summary>
            /// The txt_password item.
            /// </summary>
            [RepositoryItem("119b93b8-c90c-4a9d-8550-844404d7a985")]
            public virtual Ranorex.InputTag txt_password
            {
                get
                {
                    return _txt_passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_password item info.
            /// </summary>
            [RepositoryItemInfo("119b93b8-c90c-4a9d-8550-844404d7a985")]
            public virtual RepoItemInfo txt_passwordInfo
            {
                get
                {
                    return _txt_passwordInfo;
                }
            }

            /// <summary>
            /// The btn_logIn item.
            /// </summary>
            [RepositoryItem("723c0aae-fee4-4a46-8d2f-8157392b719b")]
            public virtual Ranorex.InputTag btn_logIn
            {
                get
                {
                    return _btn_loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The btn_logIn item info.
            /// </summary>
            [RepositoryItemInfo("723c0aae-fee4-4a46-8d2f-8157392b719b")]
            public virtual RepoItemInfo btn_logInInfo
            {
                get
                {
                    return _btn_loginInfo;
                }
            }
        }

        /// <summary>
        /// The IncidentFormFolder folder.
        /// </summary>
        [RepositoryFolder("8902fdd3-5533-41a7-a25e-4265827b540b")]
        public partial class IncidentFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txt_customerInfo;
            RepoItemInfo _mn_assignedgroupInfo;
            RepoItemInfo _txt_descriptionInfo;
            RepoItemInfo _txt_detaileddescriptionInfo;
            RepoItemInfo _mn_impactInfo;
            RepoItemInfo _mn_urgencyInfo;
            RepoItemInfo _btn_saveInfo;
            RepoItemInfo _nextstageInfo;
            RepoItemInfo _btn_assigntomeInfo;
            RepoItemInfo _btn_save_nextstage_popupInfo;
            RepoItemInfo _mn_searchrelationshipInfo;
            RepoItemInfo _txt_searchvalueInfo;
            RepoItemInfo _btn_searchInfo;
            RepoItemInfo _tf_row_incidentidInfo;
            RepoItemInfo _btn_relateincidentassocInfo;
            RepoItemInfo _mn_relationshiptypeInfo;
            RepoItemInfo _txt_incidentidInfo;
            RepoItemInfo _mn_statusInfo;
            RepoItemInfo _mn_statusreasonInfo;
            RepoItemInfo _txt_inc_resolutionInfo;

            /// <summary>
            /// Creates a new IncidentForm  folder.
            /// </summary>
            public IncidentFormFolder(RepoGenBaseFolder parentFolder) :
                    base("IncidentForm", "/dom[@domain='desktop-c80mesn']", parentFolder, 30000, null, false, "8902fdd3-5533-41a7-a25e-4265827b540b", "")
            {
                _txt_customerInfo = new RepoItemInfo(this, "txt_customer", ".//div[@arid='303530000']", 30000, null, "40b692f6-0e58-4813-a78e-ad5f28acb670");
                _mn_assignedgroupInfo = new RepoItemInfo(this, "mn_assignedGroup", ".//div[@arid='1000000217']", 30000, null, "766f03f4-ae29-417d-8c8f-adebd80ec4bc");
                _txt_descriptionInfo = new RepoItemInfo(this, "txt_description", ".//div[@arid='1000000000']", 30000, null, "0222285f-093c-4ae6-b8cf-d8bdc69227f1");
                _txt_detaileddescriptionInfo = new RepoItemInfo(this, "txt_detailedDescription", ".//div[@arid='1000000151']", 30000, null, "cd65daae-841a-42b5-8d75-a4c2d67427c5");
                _mn_impactInfo = new RepoItemInfo(this, "mn_impact", ".//div[@arid='1000000163']", 30000, null, "5ea1ccd9-081c-4ade-a4a4-3223631c8d53");
                _mn_urgencyInfo = new RepoItemInfo(this, "mn_urgency", ".//div[@arid='1000000162']", 30000, null, "c0c7a2c0-f268-488b-afae-02c6b664800f");
                _btn_saveInfo = new RepoItemInfo(this, "btn_save", ".//div[@id='FormContainer']//div[@id<'304255220']//div[@innertext='Save']", 30000, null, "bef213aa-acdb-432c-a249-be299a6b44ee");
                _nextstageInfo = new RepoItemInfo(this, "NextStage", ".//div[@innertext='Next Stage']", 30000, null, "135388ef-92cd-43fc-807d-2710ae05de9f");
                _btn_assigntomeInfo = new RepoItemInfo(this, "btn_assignToMe", ".//div[@innertext='Assign to Me']", 30000, null, "1c4cf7c5-ee1f-4ee1-bb54-4cc348b8918f");
                _btn_save_nextstage_popupInfo = new RepoItemInfo(this, "btn_save_NextStage_PopUp", ".//div[@innertext='Save']", 30000, null, "1986bb54-1f75-418a-abb1-2a78bc837ac6");
                _mn_searchrelationshipInfo = new RepoItemInfo(this, "mn_searchRelationship", ".//div[@arid='301541300']", 30000, null, "5ed1707a-36b9-4764-8b67-948f2bbd6439");
                _txt_searchvalueInfo = new RepoItemInfo(this, "txt_searchValue", ".//div[@arid='301737200']", 30000, null, "944056c6-aa47-4f4f-ad3a-56935e93a817");
                _btn_searchInfo = new RepoItemInfo(this, "btn_search", ".//div[#'FormContainer']//div[@innertext='Search']", 30000, null, "8192ba19-a5cd-4b29-b034-b3b90bf3cb54");
                _tf_row_incidentidInfo = new RepoItemInfo(this, "tf_row_incidentID", ".//div[@id<'302078000']//span[@innertext='INC000000000206']", 30000, null, "066f85ba-f1fa-4463-ba25-ac9d0673fdd9");
                _btn_relateincidentassocInfo = new RepoItemInfo(this, "btn_relateIncidentAssoc", ".//div[@innertext='Relate']", 30000, null, "02dfbc41-8354-4f46-ba15-348fbf1ac174");
                _mn_relationshiptypeInfo = new RepoItemInfo(this, "mn_relationshipType", ".//div[@arid='301527000']", 30000, null, "56c8ae4b-b939-484d-8435-c5c28474e467");
                _txt_incidentidInfo = new RepoItemInfo(this, "txt_IncidentID", ".//div[@arid='1000000161']/textarea[@tagname='textarea']", 30000, null, "8fdf67c0-3e5a-48bf-a212-2501e54ed4cc");
                _mn_statusInfo = new RepoItemInfo(this, "mn_status", ".//div[@arid='7']//div[@class='selection']/input[@visible='True']", 30000, null, "9957a7e1-2f97-4ff1-8347-e4a17e915429");
                _mn_statusreasonInfo = new RepoItemInfo(this, "mn_statusReason", ".//div[@arid='1000000881']//textarea", 30000, null, "93e0a513-ce9f-478d-8df0-c3c3182fb445");
                _txt_inc_resolutionInfo = new RepoItemInfo(this, "txt_INC_Resolution", ".//div[@arid='1000000156']//textarea", 30000, null, "7c4aa71a-8ad4-4def-88d4-aa515b3e422a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8902fdd3-5533-41a7-a25e-4265827b540b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8902fdd3-5533-41a7-a25e-4265827b540b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txt_customer item.
            /// </summary>
            [RepositoryItem("40b692f6-0e58-4813-a78e-ad5f28acb670")]
            public virtual Ranorex.DivTag txt_customer
            {
                get
                {
                    return _txt_customerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The txt_customer item info.
            /// </summary>
            [RepositoryItemInfo("40b692f6-0e58-4813-a78e-ad5f28acb670")]
            public virtual RepoItemInfo txt_customerInfo
            {
                get
                {
                    return _txt_customerInfo;
                }
            }

            /// <summary>
            /// The mn_assignedGroup item.
            /// </summary>
            [RepositoryItem("766f03f4-ae29-417d-8c8f-adebd80ec4bc")]
            public virtual Ranorex.DivTag mn_assignedGroup
            {
                get
                {
                    return _mn_assignedgroupInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The mn_assignedGroup item info.
            /// </summary>
            [RepositoryItemInfo("766f03f4-ae29-417d-8c8f-adebd80ec4bc")]
            public virtual RepoItemInfo mn_assignedGroupInfo
            {
                get
                {
                    return _mn_assignedgroupInfo;
                }
            }

            /// <summary>
            /// The txt_description item.
            /// </summary>
            [RepositoryItem("0222285f-093c-4ae6-b8cf-d8bdc69227f1")]
            public virtual Ranorex.DivTag txt_description
            {
                get
                {
                    return _txt_descriptionInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The txt_description item info.
            /// </summary>
            [RepositoryItemInfo("0222285f-093c-4ae6-b8cf-d8bdc69227f1")]
            public virtual RepoItemInfo txt_descriptionInfo
            {
                get
                {
                    return _txt_descriptionInfo;
                }
            }

            /// <summary>
            /// The txt_detailedDescription item.
            /// </summary>
            [RepositoryItem("cd65daae-841a-42b5-8d75-a4c2d67427c5")]
            public virtual Ranorex.DivTag txt_detailedDescription
            {
                get
                {
                    return _txt_detaileddescriptionInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The txt_detailedDescription item info.
            /// </summary>
            [RepositoryItemInfo("cd65daae-841a-42b5-8d75-a4c2d67427c5")]
            public virtual RepoItemInfo txt_detailedDescriptionInfo
            {
                get
                {
                    return _txt_detaileddescriptionInfo;
                }
            }

            /// <summary>
            /// The mn_impact item.
            /// </summary>
            [RepositoryItem("5ea1ccd9-081c-4ade-a4a4-3223631c8d53")]
            public virtual Ranorex.DivTag mn_impact
            {
                get
                {
                    return _mn_impactInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The mn_impact item info.
            /// </summary>
            [RepositoryItemInfo("5ea1ccd9-081c-4ade-a4a4-3223631c8d53")]
            public virtual RepoItemInfo mn_impactInfo
            {
                get
                {
                    return _mn_impactInfo;
                }
            }

            /// <summary>
            /// The mn_urgency item.
            /// </summary>
            [RepositoryItem("c0c7a2c0-f268-488b-afae-02c6b664800f")]
            public virtual Ranorex.DivTag mn_urgency
            {
                get
                {
                    return _mn_urgencyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The mn_urgency item info.
            /// </summary>
            [RepositoryItemInfo("c0c7a2c0-f268-488b-afae-02c6b664800f")]
            public virtual RepoItemInfo mn_urgencyInfo
            {
                get
                {
                    return _mn_urgencyInfo;
                }
            }

            /// <summary>
            /// The btn_save item.
            /// </summary>
            [RepositoryItem("bef213aa-acdb-432c-a249-be299a6b44ee")]
            public virtual Ranorex.DivTag btn_save
            {
                get
                {
                    return _btn_saveInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The btn_save item info.
            /// </summary>
            [RepositoryItemInfo("bef213aa-acdb-432c-a249-be299a6b44ee")]
            public virtual RepoItemInfo btn_saveInfo
            {
                get
                {
                    return _btn_saveInfo;
                }
            }

            /// <summary>
            /// The NextStage item.
            /// </summary>
            [RepositoryItem("135388ef-92cd-43fc-807d-2710ae05de9f")]
            public virtual Ranorex.DivTag NextStage
            {
                get
                {
                    return _nextstageInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NextStage item info.
            /// </summary>
            [RepositoryItemInfo("135388ef-92cd-43fc-807d-2710ae05de9f")]
            public virtual RepoItemInfo NextStageInfo
            {
                get
                {
                    return _nextstageInfo;
                }
            }

            /// <summary>
            /// The btn_assignToMe item.
            /// </summary>
            [RepositoryItem("1c4cf7c5-ee1f-4ee1-bb54-4cc348b8918f")]
            public virtual Ranorex.DivTag btn_assignToMe
            {
                get
                {
                    return _btn_assigntomeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The btn_assignToMe item info.
            /// </summary>
            [RepositoryItemInfo("1c4cf7c5-ee1f-4ee1-bb54-4cc348b8918f")]
            public virtual RepoItemInfo btn_assignToMeInfo
            {
                get
                {
                    return _btn_assigntomeInfo;
                }
            }

            /// <summary>
            /// The btn_save_NextStage_PopUp item.
            /// </summary>
            [RepositoryItem("1986bb54-1f75-418a-abb1-2a78bc837ac6")]
            public virtual Ranorex.DivTag btn_save_NextStage_PopUp
            {
                get
                {
                    return _btn_save_nextstage_popupInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The btn_save_NextStage_PopUp item info.
            /// </summary>
            [RepositoryItemInfo("1986bb54-1f75-418a-abb1-2a78bc837ac6")]
            public virtual RepoItemInfo btn_save_NextStage_PopUpInfo
            {
                get
                {
                    return _btn_save_nextstage_popupInfo;
                }
            }

            /// <summary>
            /// The mn_searchRelationship item.
            /// </summary>
            [RepositoryItem("5ed1707a-36b9-4764-8b67-948f2bbd6439")]
            public virtual Ranorex.DivTag mn_searchRelationship
            {
                get
                {
                    return _mn_searchrelationshipInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The mn_searchRelationship item info.
            /// </summary>
            [RepositoryItemInfo("5ed1707a-36b9-4764-8b67-948f2bbd6439")]
            public virtual RepoItemInfo mn_searchRelationshipInfo
            {
                get
                {
                    return _mn_searchrelationshipInfo;
                }
            }

            /// <summary>
            /// The txt_searchValue item.
            /// </summary>
            [RepositoryItem("944056c6-aa47-4f4f-ad3a-56935e93a817")]
            public virtual Ranorex.DivTag txt_searchValue
            {
                get
                {
                    return _txt_searchvalueInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The txt_searchValue item info.
            /// </summary>
            [RepositoryItemInfo("944056c6-aa47-4f4f-ad3a-56935e93a817")]
            public virtual RepoItemInfo txt_searchValueInfo
            {
                get
                {
                    return _txt_searchvalueInfo;
                }
            }

            /// <summary>
            /// The btn_search item.
            /// </summary>
            [RepositoryItem("8192ba19-a5cd-4b29-b034-b3b90bf3cb54")]
            public virtual Ranorex.DivTag btn_search
            {
                get
                {
                    return _btn_searchInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The btn_search item info.
            /// </summary>
            [RepositoryItemInfo("8192ba19-a5cd-4b29-b034-b3b90bf3cb54")]
            public virtual RepoItemInfo btn_searchInfo
            {
                get
                {
                    return _btn_searchInfo;
                }
            }

            /// <summary>
            /// The tf_row_incidentID item.
            /// </summary>
            [RepositoryItem("066f85ba-f1fa-4463-ba25-ac9d0673fdd9")]
            public virtual Ranorex.SpanTag tf_row_incidentID
            {
                get
                {
                    return _tf_row_incidentidInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The tf_row_incidentID item info.
            /// </summary>
            [RepositoryItemInfo("066f85ba-f1fa-4463-ba25-ac9d0673fdd9")]
            public virtual RepoItemInfo tf_row_incidentIDInfo
            {
                get
                {
                    return _tf_row_incidentidInfo;
                }
            }

            /// <summary>
            /// The btn_relateIncidentAssoc item.
            /// </summary>
            [RepositoryItem("02dfbc41-8354-4f46-ba15-348fbf1ac174")]
            public virtual Ranorex.DivTag btn_relateIncidentAssoc
            {
                get
                {
                    return _btn_relateincidentassocInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The btn_relateIncidentAssoc item info.
            /// </summary>
            [RepositoryItemInfo("02dfbc41-8354-4f46-ba15-348fbf1ac174")]
            public virtual RepoItemInfo btn_relateIncidentAssocInfo
            {
                get
                {
                    return _btn_relateincidentassocInfo;
                }
            }

            /// <summary>
            /// The mn_relationshipType item.
            /// </summary>
            [RepositoryItem("56c8ae4b-b939-484d-8435-c5c28474e467")]
            public virtual Ranorex.DivTag mn_relationshipType
            {
                get
                {
                    return _mn_relationshiptypeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The mn_relationshipType item info.
            /// </summary>
            [RepositoryItemInfo("56c8ae4b-b939-484d-8435-c5c28474e467")]
            public virtual RepoItemInfo mn_relationshipTypeInfo
            {
                get
                {
                    return _mn_relationshiptypeInfo;
                }
            }

            /// <summary>
            /// The txt_IncidentID item.
            /// </summary>
            [RepositoryItem("8fdf67c0-3e5a-48bf-a212-2501e54ed4cc")]
            public virtual Ranorex.TextAreaTag txt_IncidentID
            {
                get
                {
                    return _txt_incidentidInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The txt_IncidentID item info.
            /// </summary>
            [RepositoryItemInfo("8fdf67c0-3e5a-48bf-a212-2501e54ed4cc")]
            public virtual RepoItemInfo txt_IncidentIDInfo
            {
                get
                {
                    return _txt_incidentidInfo;
                }
            }

            /// <summary>
            /// The mn_status item.
            /// </summary>
            [RepositoryItem("9957a7e1-2f97-4ff1-8347-e4a17e915429")]
            public virtual Ranorex.InputTag mn_status
            {
                get
                {
                    return _mn_statusInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The mn_status item info.
            /// </summary>
            [RepositoryItemInfo("9957a7e1-2f97-4ff1-8347-e4a17e915429")]
            public virtual RepoItemInfo mn_statusInfo
            {
                get
                {
                    return _mn_statusInfo;
                }
            }

            /// <summary>
            /// The mn_statusReason item.
            /// </summary>
            [RepositoryItem("93e0a513-ce9f-478d-8df0-c3c3182fb445")]
            public virtual Ranorex.TextAreaTag mn_statusReason
            {
                get
                {
                    return _mn_statusreasonInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The mn_statusReason item info.
            /// </summary>
            [RepositoryItemInfo("93e0a513-ce9f-478d-8df0-c3c3182fb445")]
            public virtual RepoItemInfo mn_statusReasonInfo
            {
                get
                {
                    return _mn_statusreasonInfo;
                }
            }

            /// <summary>
            /// The txt_INC_Resolution item.
            /// </summary>
            [RepositoryItem("7c4aa71a-8ad4-4def-88d4-aa515b3e422a")]
            public virtual Ranorex.TextAreaTag txt_INC_Resolution
            {
                get
                {
                    return _txt_inc_resolutionInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The txt_INC_Resolution item info.
            /// </summary>
            [RepositoryItemInfo("7c4aa71a-8ad4-4def-88d4-aa515b3e422a")]
            public virtual RepoItemInfo txt_INC_ResolutionInfo
            {
                get
                {
                    return _txt_inc_resolutionInfo;
                }
            }
        }

        /// <summary>
        /// The BMCRemedySearchAppFolder folder.
        /// </summary>
        [RepositoryFolder("eba120b7-e883-4be3-9c39-73117f3175ef")]
        public partial class BMCRemedySearchAppFolder : RepoGenBaseFolder
        {
            SwissComRepoFolders.PageBodyPbChromeFolder _pagebodypbchrome;
            SwissComRepoFolders.FormContainerFolder _formcontainer;
            RepoItemInfo _tdtag3moderatelimited1Info;
            RepoItemInfo _tdtag3medium1Info;
            RepoItemInfo _pagebodypbchrome1Info;
            RepoItemInfo _yuiskinsamInfo;
            RepoItemInfo _atagokInfo;
            RepoItemInfo _newitemInfo;
            RepoItemInfo _tbsearchsavechangesInfo;
            RepoItemInfo _logoutInfo;

            /// <summary>
            /// Creates a new BMCRemedySearch  folder.
            /// </summary>
            public BMCRemedySearchAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BMCRemedySearch", "/dom[@domain='desktop-c80mesn']", parentFolder, 5000, null, false, "eba120b7-e883-4be3-9c39-73117f3175ef", "")
            {
                _pagebodypbchrome = new SwissComRepoFolders.PageBodyPbChromeFolder(this);
                _formcontainer = new SwissComRepoFolders.FormContainerFolder(this);
                _tdtag3moderatelimited1Info = new RepoItemInfo(this, "TdTag3ModerateLimited1", "body/div[3]/?/?/table/tbody/tr[3]/td[@innertext='3-Moderate/Limited']", 30000, null, "32ecdfce-ad23-41a4-ae7d-67dfa59565f3");
                _tdtag3medium1Info = new RepoItemInfo(this, "TdTag3Medium1", "body/div[3]/?/?/table/tbody/tr[3]/td[@innertext='3-Medium']", 30000, null, "98dfbfd7-392e-4578-b513-10e6d0e0e4b2");
                _pagebodypbchrome1Info = new RepoItemInfo(this, "PageBodyPbChrome1", ".//div[#'FormContainer']/div[2]/div/div/div[3]/fieldset/div/div/div/div/div[2]/fieldset/div/?/?/div[@id='FormApp']/div[@id='FormContainer']/div[4]/div/div/div[2]/fieldset/div/div/div/div/div[1]/fieldset/div/div/div/div/div[1]/fieldset/div/div/div/div/div[2]/fieldset/div", 30000, null, "f8101db2-fbfc-44bb-9a1d-c4b050c9b56d");
                _yuiskinsamInfo = new RepoItemInfo(this, "YuiSkinSam", "body", 30000, null, "e1d13286-65cf-41f2-83b4-7539d5652e8a");
                _atagokInfo = new RepoItemInfo(this, "ATagOK", ".//table[#'DivTable']//iframe[@src='http://desktop-c80mesn/arsys/resources/html/MessagePopup.html']//div[#'PopupMsgFooter']/a[@innertext='OK']", 30000, null, "0bd5bd93-1346-44cc-b89c-80c578110cb1");
                _newitemInfo = new RepoItemInfo(this, "NewItem", "element", 30000, null, "bc33373a-b271-4e79-b715-76349019769e");
                _tbsearchsavechangesInfo = new RepoItemInfo(this, "TBsearchsavechanges", ".//div[#'TBsearchsavechanges']", 30000, null, "3987624e-684d-4a82-b5f3-cd8c4078c9c3");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//div[@id<'300000044']", 30000, null, "b918a171-6f2a-4c21-a21b-c41e3c0e82ae");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eba120b7-e883-4be3-9c39-73117f3175ef")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eba120b7-e883-4be3-9c39-73117f3175ef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TdTag3ModerateLimited1 item.
            /// </summary>
            [RepositoryItem("32ecdfce-ad23-41a4-ae7d-67dfa59565f3")]
            public virtual Ranorex.TdTag TdTag3ModerateLimited1
            {
                get
                {
                    return _tdtag3moderatelimited1Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The TdTag3ModerateLimited1 item info.
            /// </summary>
            [RepositoryItemInfo("32ecdfce-ad23-41a4-ae7d-67dfa59565f3")]
            public virtual RepoItemInfo TdTag3ModerateLimited1Info
            {
                get
                {
                    return _tdtag3moderatelimited1Info;
                }
            }

            /// <summary>
            /// The TdTag3Medium1 item.
            /// </summary>
            [RepositoryItem("98dfbfd7-392e-4578-b513-10e6d0e0e4b2")]
            public virtual Ranorex.TdTag TdTag3Medium1
            {
                get
                {
                    return _tdtag3medium1Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The TdTag3Medium1 item info.
            /// </summary>
            [RepositoryItemInfo("98dfbfd7-392e-4578-b513-10e6d0e0e4b2")]
            public virtual RepoItemInfo TdTag3Medium1Info
            {
                get
                {
                    return _tdtag3medium1Info;
                }
            }

            /// <summary>
            /// The PageBodyPbChrome1 item.
            /// </summary>
            [RepositoryItem("f8101db2-fbfc-44bb-9a1d-c4b050c9b56d")]
            public virtual Ranorex.DivTag PageBodyPbChrome1
            {
                get
                {
                    return _pagebodypbchrome1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PageBodyPbChrome1 item info.
            /// </summary>
            [RepositoryItemInfo("f8101db2-fbfc-44bb-9a1d-c4b050c9b56d")]
            public virtual RepoItemInfo PageBodyPbChrome1Info
            {
                get
                {
                    return _pagebodypbchrome1Info;
                }
            }

            /// <summary>
            /// The YuiSkinSam item.
            /// </summary>
            [RepositoryItem("e1d13286-65cf-41f2-83b4-7539d5652e8a")]
            public virtual Ranorex.BodyTag YuiSkinSam
            {
                get
                {
                    return _yuiskinsamInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The YuiSkinSam item info.
            /// </summary>
            [RepositoryItemInfo("e1d13286-65cf-41f2-83b4-7539d5652e8a")]
            public virtual RepoItemInfo YuiSkinSamInfo
            {
                get
                {
                    return _yuiskinsamInfo;
                }
            }

            /// <summary>
            /// The ATagOK item.
            /// </summary>
            [RepositoryItem("0bd5bd93-1346-44cc-b89c-80c578110cb1")]
            public virtual Ranorex.ATag ATagOK
            {
                get
                {
                    return _atagokInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagOK item info.
            /// </summary>
            [RepositoryItemInfo("0bd5bd93-1346-44cc-b89c-80c578110cb1")]
            public virtual RepoItemInfo ATagOKInfo
            {
                get
                {
                    return _atagokInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("bc33373a-b271-4e79-b715-76349019769e")]
            public virtual Ranorex.Unknown NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("bc33373a-b271-4e79-b715-76349019769e")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }

            /// <summary>
            /// The TBsearchsavechanges item.
            /// </summary>
            [RepositoryItem("3987624e-684d-4a82-b5f3-cd8c4078c9c3")]
            public virtual Ranorex.DivTag TBsearchsavechanges
            {
                get
                {
                    return _tbsearchsavechangesInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TBsearchsavechanges item info.
            /// </summary>
            [RepositoryItemInfo("3987624e-684d-4a82-b5f3-cd8c4078c9c3")]
            public virtual RepoItemInfo TBsearchsavechangesInfo
            {
                get
                {
                    return _tbsearchsavechangesInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("b918a171-6f2a-4c21-a21b-c41e3c0e82ae")]
            public virtual Ranorex.DivTag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("b918a171-6f2a-4c21-a21b-c41e3c0e82ae")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The PageBodyPbChrome folder.
            /// </summary>
            [RepositoryFolder("b96f80c5-3073-49cf-9550-a6a6102dd582")]
            public virtual SwissComRepoFolders.PageBodyPbChromeFolder PageBodyPbChrome
            {
                get { return _pagebodypbchrome; }
            }

            /// <summary>
            /// The FormContainer folder.
            /// </summary>
            [RepositoryFolder("45a32c9c-4a76-4c6c-b37f-f9fe06a80b0a")]
            public virtual SwissComRepoFolders.FormContainerFolder FormContainer
            {
                get { return _formcontainer; }
            }
        }

        /// <summary>
        /// The PageBodyPbChromeFolder folder.
        /// </summary>
        [RepositoryFolder("b96f80c5-3073-49cf-9550-a6a6102dd582")]
        public partial class PageBodyPbChromeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _false2Info;
            RepoItemInfo _text1Info;
            RepoItemInfo _fieldsettagpnl1Info;
            RepoItemInfo _fieldsettagpnl2Info;
            RepoItemInfo _fieldsettagpnl3Info;
            RepoItemInfo _ardbncustomerarfid303530000chardfInfo;
            RepoItemInfo _fieldsettagpnl4Info;
            RepoItemInfo _ardbnz2phincidentinformationarfid30371Info;
            RepoItemInfo _ardbnimpactarfid1000000163dfenumselInfo;
            RepoItemInfo _ardbnz2phbasicincidentinformationarfidInfo;
            RepoItemInfo _ardbnstatusarfid7dfenumselInfo;
            RepoItemInfo _pendingoriginalincidentInfo;
            RepoItemInfo _pendingInfo;

            /// <summary>
            /// Creates a new PageBodyPbChrome  folder.
            /// </summary>
            public PageBodyPbChromeFolder(RepoGenBaseFolder parentFolder) :
                    base("PageBodyPbChrome", ".//div[#'FormContainer']/div[4]/div/div/div[2]/fieldset/div/div/div/div/div[2]/fieldset/div", parentFolder, 5000, null, false, "b96f80c5-3073-49cf-9550-a6a6102dd582", "")
            {
                _false2Info = new RepoItemInfo(this, "False2", "?/?/fieldset/div[4]/fieldset/div[1]/textarea[@title='']", 30000, null, "b3921815-07d3-4b18-aef4-63c4487e822a");
                _text1Info = new RepoItemInfo(this, "Text1", "?/?/fieldset/div[3]/fieldset/div[4]/div/input[@title='']", 30000, null, "9a0cc00d-ec8b-460e-83dc-0f428994265f");
                _fieldsettagpnl1Info = new RepoItemInfo(this, "FieldSetTagPnl1", "?/?/fieldset/div[2]/fieldset", 30000, null, "ce4db886-c351-4be2-a1d5-37f1ec6f1ace");
                _fieldsettagpnl2Info = new RepoItemInfo(this, "FieldSetTagPnl2", "?/?/fieldset/div[3]/fieldset", 30000, null, "7ca4b524-aafa-48c7-9335-9c4009bf812c");
                _fieldsettagpnl3Info = new RepoItemInfo(this, "FieldSetTagPnl3", "?/?/fieldset/div[4]/fieldset", 30000, null, "b273a5f7-82cf-4e0d-b984-1238841d1ac7");
                _ardbncustomerarfid303530000chardfInfo = new RepoItemInfo(this, "ArdbnCustomerArfid303530000CharDf", "?/?/fieldset/div[1]/fieldset/div[3]", 30000, null, "38d4d1b9-380b-4fb5-9928-4ca6193e6b50");
                _fieldsettagpnl4Info = new RepoItemInfo(this, "FieldSetTagPnl4", "?/?/fieldset", 30000, null, "e8fa6e2d-b17b-4854-98f3-6aab39286788");
                _ardbnz2phincidentinformationarfid30371Info = new RepoItemInfo(this, "Ardbnz2PHIncidentInformationArfid30371", "?/?/fieldset/div[2]", 30000, null, "58816b1e-364b-459d-b803-e6b68a7cfa56");
                _ardbnimpactarfid1000000163dfenumselInfo = new RepoItemInfo(this, "ArdbnImpactArfid1000000163DfEnumSel", "?/?/fieldset/div[3]/fieldset/div[8]", 30000, null, "6aa97f5a-81c0-4b90-a607-bbdfd63b6c99");
                _ardbnz2phbasicincidentinformationarfidInfo = new RepoItemInfo(this, "Ardbnz2PHBasicIncidentInformationArfid", "?/?/fieldset/div[1]", 30000, null, "c2f3af0c-2992-4c43-8f7c-e11dc372fcda");
                _ardbnstatusarfid7dfenumselInfo = new RepoItemInfo(this, "ArdbnStatusArfid7DfEnumSel", "?/?/fieldset/div[4]/fieldset/div[5]", 30000, null, "ce9409ac-3777-48b8-a70f-3ca8995c4041");
                _pendingoriginalincidentInfo = new RepoItemInfo(this, "PendingOriginalIncident", "?/?/fieldset/div[4]/fieldset/div[6]/textarea[@title='Pending Original Incident']", 30000, null, "d853b0f7-eaf1-40b3-887d-083d6676470e");
                _pendingInfo = new RepoItemInfo(this, "Pending", "?/?/fieldset/div[4]/fieldset/div[5]/div/input[@title='Pending']", 30000, null, "8b40b3d9-15b8-492b-bf26-3c617f689716");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b96f80c5-3073-49cf-9550-a6a6102dd582")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b96f80c5-3073-49cf-9550-a6a6102dd582")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The False2 item.
            /// </summary>
            [RepositoryItem("b3921815-07d3-4b18-aef4-63c4487e822a")]
            public virtual Ranorex.TextAreaTag False2
            {
                get
                {
                    return _false2Info.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The False2 item info.
            /// </summary>
            [RepositoryItemInfo("b3921815-07d3-4b18-aef4-63c4487e822a")]
            public virtual RepoItemInfo False2Info
            {
                get
                {
                    return _false2Info;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("9a0cc00d-ec8b-460e-83dc-0f428994265f")]
            public virtual Ranorex.InputTag Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("9a0cc00d-ec8b-460e-83dc-0f428994265f")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The FieldSetTagPnl1 item.
            /// </summary>
            [RepositoryItem("ce4db886-c351-4be2-a1d5-37f1ec6f1ace")]
            public virtual Ranorex.FieldSetTag FieldSetTagPnl1
            {
                get
                {
                    return _fieldsettagpnl1Info.CreateAdapter<Ranorex.FieldSetTag>(true);
                }
            }

            /// <summary>
            /// The FieldSetTagPnl1 item info.
            /// </summary>
            [RepositoryItemInfo("ce4db886-c351-4be2-a1d5-37f1ec6f1ace")]
            public virtual RepoItemInfo FieldSetTagPnl1Info
            {
                get
                {
                    return _fieldsettagpnl1Info;
                }
            }

            /// <summary>
            /// The FieldSetTagPnl2 item.
            /// </summary>
            [RepositoryItem("7ca4b524-aafa-48c7-9335-9c4009bf812c")]
            public virtual Ranorex.FieldSetTag FieldSetTagPnl2
            {
                get
                {
                    return _fieldsettagpnl2Info.CreateAdapter<Ranorex.FieldSetTag>(true);
                }
            }

            /// <summary>
            /// The FieldSetTagPnl2 item info.
            /// </summary>
            [RepositoryItemInfo("7ca4b524-aafa-48c7-9335-9c4009bf812c")]
            public virtual RepoItemInfo FieldSetTagPnl2Info
            {
                get
                {
                    return _fieldsettagpnl2Info;
                }
            }

            /// <summary>
            /// The FieldSetTagPnl3 item.
            /// </summary>
            [RepositoryItem("b273a5f7-82cf-4e0d-b984-1238841d1ac7")]
            public virtual Ranorex.FieldSetTag FieldSetTagPnl3
            {
                get
                {
                    return _fieldsettagpnl3Info.CreateAdapter<Ranorex.FieldSetTag>(true);
                }
            }

            /// <summary>
            /// The FieldSetTagPnl3 item info.
            /// </summary>
            [RepositoryItemInfo("b273a5f7-82cf-4e0d-b984-1238841d1ac7")]
            public virtual RepoItemInfo FieldSetTagPnl3Info
            {
                get
                {
                    return _fieldsettagpnl3Info;
                }
            }

            /// <summary>
            /// The ArdbnCustomerArfid303530000CharDf item.
            /// </summary>
            [RepositoryItem("38d4d1b9-380b-4fb5-9928-4ca6193e6b50")]
            public virtual Ranorex.DivTag ArdbnCustomerArfid303530000CharDf
            {
                get
                {
                    return _ardbncustomerarfid303530000chardfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ArdbnCustomerArfid303530000CharDf item info.
            /// </summary>
            [RepositoryItemInfo("38d4d1b9-380b-4fb5-9928-4ca6193e6b50")]
            public virtual RepoItemInfo ArdbnCustomerArfid303530000CharDfInfo
            {
                get
                {
                    return _ardbncustomerarfid303530000chardfInfo;
                }
            }

            /// <summary>
            /// The FieldSetTagPnl4 item.
            /// </summary>
            [RepositoryItem("e8fa6e2d-b17b-4854-98f3-6aab39286788")]
            public virtual Ranorex.FieldSetTag FieldSetTagPnl4
            {
                get
                {
                    return _fieldsettagpnl4Info.CreateAdapter<Ranorex.FieldSetTag>(true);
                }
            }

            /// <summary>
            /// The FieldSetTagPnl4 item info.
            /// </summary>
            [RepositoryItemInfo("e8fa6e2d-b17b-4854-98f3-6aab39286788")]
            public virtual RepoItemInfo FieldSetTagPnl4Info
            {
                get
                {
                    return _fieldsettagpnl4Info;
                }
            }

            /// <summary>
            /// The Ardbnz2PHIncidentInformationArfid30371 item.
            /// </summary>
            [RepositoryItem("58816b1e-364b-459d-b803-e6b68a7cfa56")]
            public virtual Ranorex.DivTag Ardbnz2PHIncidentInformationArfid30371
            {
                get
                {
                    return _ardbnz2phincidentinformationarfid30371Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Ardbnz2PHIncidentInformationArfid30371 item info.
            /// </summary>
            [RepositoryItemInfo("58816b1e-364b-459d-b803-e6b68a7cfa56")]
            public virtual RepoItemInfo Ardbnz2PHIncidentInformationArfid30371Info
            {
                get
                {
                    return _ardbnz2phincidentinformationarfid30371Info;
                }
            }

            /// <summary>
            /// The ArdbnImpactArfid1000000163DfEnumSel item.
            /// </summary>
            [RepositoryItem("6aa97f5a-81c0-4b90-a607-bbdfd63b6c99")]
            public virtual Ranorex.DivTag ArdbnImpactArfid1000000163DfEnumSel
            {
                get
                {
                    return _ardbnimpactarfid1000000163dfenumselInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ArdbnImpactArfid1000000163DfEnumSel item info.
            /// </summary>
            [RepositoryItemInfo("6aa97f5a-81c0-4b90-a607-bbdfd63b6c99")]
            public virtual RepoItemInfo ArdbnImpactArfid1000000163DfEnumSelInfo
            {
                get
                {
                    return _ardbnimpactarfid1000000163dfenumselInfo;
                }
            }

            /// <summary>
            /// The Ardbnz2PHBasicIncidentInformationArfid item.
            /// </summary>
            [RepositoryItem("c2f3af0c-2992-4c43-8f7c-e11dc372fcda")]
            public virtual Ranorex.DivTag Ardbnz2PHBasicIncidentInformationArfid
            {
                get
                {
                    return _ardbnz2phbasicincidentinformationarfidInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Ardbnz2PHBasicIncidentInformationArfid item info.
            /// </summary>
            [RepositoryItemInfo("c2f3af0c-2992-4c43-8f7c-e11dc372fcda")]
            public virtual RepoItemInfo Ardbnz2PHBasicIncidentInformationArfidInfo
            {
                get
                {
                    return _ardbnz2phbasicincidentinformationarfidInfo;
                }
            }

            /// <summary>
            /// The ArdbnStatusArfid7DfEnumSel item.
            /// </summary>
            [RepositoryItem("ce9409ac-3777-48b8-a70f-3ca8995c4041")]
            public virtual Ranorex.DivTag ArdbnStatusArfid7DfEnumSel
            {
                get
                {
                    return _ardbnstatusarfid7dfenumselInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ArdbnStatusArfid7DfEnumSel item info.
            /// </summary>
            [RepositoryItemInfo("ce9409ac-3777-48b8-a70f-3ca8995c4041")]
            public virtual RepoItemInfo ArdbnStatusArfid7DfEnumSelInfo
            {
                get
                {
                    return _ardbnstatusarfid7dfenumselInfo;
                }
            }

            /// <summary>
            /// The PendingOriginalIncident item.
            /// </summary>
            [RepositoryItem("d853b0f7-eaf1-40b3-887d-083d6676470e")]
            public virtual Ranorex.TextAreaTag PendingOriginalIncident
            {
                get
                {
                    return _pendingoriginalincidentInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The PendingOriginalIncident item info.
            /// </summary>
            [RepositoryItemInfo("d853b0f7-eaf1-40b3-887d-083d6676470e")]
            public virtual RepoItemInfo PendingOriginalIncidentInfo
            {
                get
                {
                    return _pendingoriginalincidentInfo;
                }
            }

            /// <summary>
            /// The Pending item.
            /// </summary>
            [RepositoryItem("8b40b3d9-15b8-492b-bf26-3c617f689716")]
            public virtual Ranorex.InputTag Pending
            {
                get
                {
                    return _pendingInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Pending item info.
            /// </summary>
            [RepositoryItemInfo("8b40b3d9-15b8-492b-bf26-3c617f689716")]
            public virtual RepoItemInfo PendingInfo
            {
                get
                {
                    return _pendingInfo;
                }
            }
        }

        /// <summary>
        /// The FormContainerFolder folder.
        /// </summary>
        [RepositoryFolder("45a32c9c-4a76-4c6c-b37f-f9fe06a80b0a")]
        public partial class FormContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _relationshipsInfo;
            RepoItemInfo _incidentInfo;
            RepoItemInfo _basetableinnerInfo;
            RepoItemInfo _pagebodypbchromeInfo;
            RepoItemInfo _false2Info;
            RepoItemInfo _false4Info;
            RepoItemInfo _textInfo;
            RepoItemInfo _searchInfo;
            RepoItemInfo _ardbnimpactarfid1000000163dfenumselInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _javascriptInfo;
            RepoItemInfo _ardbnz5boxsearchcriteriaarfid30157300Info;
            RepoItemInfo _usebasicsearchInfo;
            RepoItemInfo _nobrInfo;
            RepoItemInfo _testsummaryInfo;
            RepoItemInfo _relateInfo;
            RepoItemInfo _newitemInfo;
            RepoItemInfo _inc0000000000681Info;

            /// <summary>
            /// Creates a new FormContainer  folder.
            /// </summary>
            public FormContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("FormContainer", ".//div[#'FormContainer']", parentFolder, 30000, null, false, "45a32c9c-4a76-4c6c-b37f-f9fe06a80b0a", "")
            {
                _relationshipsInfo = new RepoItemInfo(this, "Relationships", ".//a[@innertext='Relationships']", 30000, null, "e85fe7bb-c2ea-4c88-baae-7794d159d1ca");
                _incidentInfo = new RepoItemInfo(this, "Incident", "div[2]/div/div/div[3]/fieldset/div/div/div/div/div[2]/fieldset/div/?/?/div[@id='FormApp']/div[@id='FormContainer']/div[4]/div/div/div[2]/fieldset/div/div/div/div/div[3]/fieldset/div/div/fieldset[4]/div[2]/div/div/div[4]/fieldset/div/div[1]/textarea[@title='Incident']", 30000, null, "a5484ff4-cda1-49a8-bb89-03b27ca18ccb");
                _basetableinnerInfo = new RepoItemInfo(this, "BaseTableInner", "div[2]/div/div/div[3]/fieldset/div/div/div/div/div[2]/fieldset/div/?/?/div[@id='FormApp']/div[@id='FormContainer']/div[4]/div/div/div[2]/fieldset/div/div/div/div/div[3]/fieldset/div/div/fieldset[4]/div[2]/div/div/div[2]/fieldset/div/div/div[2]/div/div[2]", 30000, null, "0c75f7b1-3fae-40cb-997f-8e8b2e37fbbe");
                _pagebodypbchromeInfo = new RepoItemInfo(this, "PageBodyPbChrome", "div[2]/div/div/div[3]/fieldset/div/div/div/div/div[2]/fieldset/div/?/?/div[@id='FormApp']/div[@id='FormContainer']/div[4]/div/div/div[2]/fieldset/div/div/div/div/div[3]/fieldset/div/div/fieldset[4]/div[2]/div/div/div[4]/fieldset/div", 30000, null, "80af58cb-7d7d-40ac-b59b-a67eb15a06f0");
                _false2Info = new RepoItemInfo(this, "False2", "div[3]/div/div/div[2]/fieldset/div/div/textarea[@required='False']", 30000, null, "cfedc9f7-1015-4f7a-afda-aa2777bb527c");
                _false4Info = new RepoItemInfo(this, "False4", "div[3]//fieldset/div/div[3]/fieldset[1]/div[4]/textarea[@required='False']", 30000, null, "be9192a0-1748-4fbb-9195-28ef98bb60a3");
                _textInfo = new RepoItemInfo(this, "Text", "div[3]//fieldset/div/div[3]/fieldset[1]/div[6]/?/?/input[@title='']", 30000, null, "50ba35ac-8a87-43aa-a602-6af28354181b");
                _searchInfo = new RepoItemInfo(this, "Search", "div[3]/div/div/div[1]/fieldset/div/div[3]/div[2]/div[2]/?/?/dl/dd[1]/?/?/a[@innertext='Search']", 30000, null, "4f18d0db-46f5-49c2-bd3b-8ddf42810e1b");
                _ardbnimpactarfid1000000163dfenumselInfo = new RepoItemInfo(this, "ArdbnImpactArfid1000000163DfEnumSel", "div[3]//fieldset/div/div[3]/fieldset[1]/div[7]", 30000, null, "3ec64237-d20e-4ad7-8813-9a750b57c4ea");
                _text1Info = new RepoItemInfo(this, "Text1", "div[@id='arid_WIN_0_1000000163']", 30000, null, "6a5baef8-96d9-4487-9fe2-92371234d16a");
                _javascriptInfo = new RepoItemInfo(this, "Javascript", "div[3]/div/div/div[1]/fieldset/div/a[2]", 30000, null, "4f396fa7-c628-4bad-bc5e-b455eacf440f");
                _ardbnz5boxsearchcriteriaarfid30157300Info = new RepoItemInfo(this, "Ardbnz5BoxSearchCriteriaArfid30157300", "div[14]", 30000, null, "d9b8ae29-d7e2-40ce-b848-628d354eb41c");
                _usebasicsearchInfo = new RepoItemInfo(this, "UseBasicSearch", "div[3]/div/div/div[1]/fieldset/div/a[1]/?/?/div[@innertext='Use Basic Search']", 30000, null, "135e797f-b131-443e-a893-73e81471cd7c");
                _nobrInfo = new RepoItemInfo(this, "Nobr", "div[3]/div/div/div[1]/fieldset/div/div[1]//table[@title='']/tbody/tr[6]/td[3]/tag[@tagname='nobr']", 30000, null, "b68cc668-9f05-4883-bc06-4d5a264e1ebe");
                _testsummaryInfo = new RepoItemInfo(this, "TestSummary", "div[3]/div/div/div[1]/fieldset/div/div[1]/div[2]//table[@title='']/tbody/tr[10]/td[2]/?/?/span[@innertext='test summary']", 30000, null, "50ab632a-baf3-49a0-b360-471915c85fb8");
                _relateInfo = new RepoItemInfo(this, "Relate", "a[4]/div/div[@innertext='Relate']", 30000, null, "11905b33-bb6c-4560-b773-20f6ceb81f30");
                _newitemInfo = new RepoItemInfo(this, "NewItem", "element", 30000, null, "5fe3ab88-cf02-41e3-a874-a135184023aa");
                _inc0000000000681Info = new RepoItemInfo(this, "INC0000000000681", "div[3]/div/div/div[1]/fieldset/div/div[1]/div[2]//table[@title='']/tbody/?/?/?/?/span[@innerhtml=$INC_ID]", 30000, null, "ebc48198-7b63-42f9-b750-6d0ae6f1477b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("45a32c9c-4a76-4c6c-b37f-f9fe06a80b0a")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("45a32c9c-4a76-4c6c-b37f-f9fe06a80b0a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Relationships item.
            /// </summary>
            [RepositoryItem("e85fe7bb-c2ea-4c88-baae-7794d159d1ca")]
            public virtual Ranorex.ATag Relationships
            {
                get
                {
                    return _relationshipsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Relationships item info.
            /// </summary>
            [RepositoryItemInfo("e85fe7bb-c2ea-4c88-baae-7794d159d1ca")]
            public virtual RepoItemInfo RelationshipsInfo
            {
                get
                {
                    return _relationshipsInfo;
                }
            }

            /// <summary>
            /// The Incident item.
            /// </summary>
            [RepositoryItem("a5484ff4-cda1-49a8-bb89-03b27ca18ccb")]
            public virtual Ranorex.TextAreaTag Incident
            {
                get
                {
                    return _incidentInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The Incident item info.
            /// </summary>
            [RepositoryItemInfo("a5484ff4-cda1-49a8-bb89-03b27ca18ccb")]
            public virtual RepoItemInfo IncidentInfo
            {
                get
                {
                    return _incidentInfo;
                }
            }

            /// <summary>
            /// The BaseTableInner item.
            /// </summary>
            [RepositoryItem("0c75f7b1-3fae-40cb-997f-8e8b2e37fbbe")]
            public virtual Ranorex.DivTag BaseTableInner
            {
                get
                {
                    return _basetableinnerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BaseTableInner item info.
            /// </summary>
            [RepositoryItemInfo("0c75f7b1-3fae-40cb-997f-8e8b2e37fbbe")]
            public virtual RepoItemInfo BaseTableInnerInfo
            {
                get
                {
                    return _basetableinnerInfo;
                }
            }

            /// <summary>
            /// The PageBodyPbChrome item.
            /// </summary>
            [RepositoryItem("80af58cb-7d7d-40ac-b59b-a67eb15a06f0")]
            public virtual Ranorex.DivTag PageBodyPbChrome
            {
                get
                {
                    return _pagebodypbchromeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PageBodyPbChrome item info.
            /// </summary>
            [RepositoryItemInfo("80af58cb-7d7d-40ac-b59b-a67eb15a06f0")]
            public virtual RepoItemInfo PageBodyPbChromeInfo
            {
                get
                {
                    return _pagebodypbchromeInfo;
                }
            }

            /// <summary>
            /// The False2 item.
            /// </summary>
            [RepositoryItem("cfedc9f7-1015-4f7a-afda-aa2777bb527c")]
            public virtual Ranorex.TextAreaTag False2
            {
                get
                {
                    return _false2Info.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The False2 item info.
            /// </summary>
            [RepositoryItemInfo("cfedc9f7-1015-4f7a-afda-aa2777bb527c")]
            public virtual RepoItemInfo False2Info
            {
                get
                {
                    return _false2Info;
                }
            }

            /// <summary>
            /// The False4 item.
            /// </summary>
            [RepositoryItem("be9192a0-1748-4fbb-9195-28ef98bb60a3")]
            public virtual Ranorex.TextAreaTag False4
            {
                get
                {
                    return _false4Info.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The False4 item info.
            /// </summary>
            [RepositoryItemInfo("be9192a0-1748-4fbb-9195-28ef98bb60a3")]
            public virtual RepoItemInfo False4Info
            {
                get
                {
                    return _false4Info;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("50ba35ac-8a87-43aa-a602-6af28354181b")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("50ba35ac-8a87-43aa-a602-6af28354181b")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("4f18d0db-46f5-49c2-bd3b-8ddf42810e1b")]
            public virtual Ranorex.ATag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("4f18d0db-46f5-49c2-bd3b-8ddf42810e1b")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The ArdbnImpactArfid1000000163DfEnumSel item.
            /// </summary>
            [RepositoryItem("3ec64237-d20e-4ad7-8813-9a750b57c4ea")]
            public virtual Ranorex.DivTag ArdbnImpactArfid1000000163DfEnumSel
            {
                get
                {
                    return _ardbnimpactarfid1000000163dfenumselInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ArdbnImpactArfid1000000163DfEnumSel item info.
            /// </summary>
            [RepositoryItemInfo("3ec64237-d20e-4ad7-8813-9a750b57c4ea")]
            public virtual RepoItemInfo ArdbnImpactArfid1000000163DfEnumSelInfo
            {
                get
                {
                    return _ardbnimpactarfid1000000163dfenumselInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("6a5baef8-96d9-4487-9fe2-92371234d16a")]
            public virtual Ranorex.DivTag Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("6a5baef8-96d9-4487-9fe2-92371234d16a")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The Javascript item.
            /// </summary>
            [RepositoryItem("4f396fa7-c628-4bad-bc5e-b455eacf440f")]
            public virtual Ranorex.ATag Javascript
            {
                get
                {
                    return _javascriptInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Javascript item info.
            /// </summary>
            [RepositoryItemInfo("4f396fa7-c628-4bad-bc5e-b455eacf440f")]
            public virtual RepoItemInfo JavascriptInfo
            {
                get
                {
                    return _javascriptInfo;
                }
            }

            /// <summary>
            /// The Ardbnz5BoxSearchCriteriaArfid30157300 item.
            /// </summary>
            [RepositoryItem("d9b8ae29-d7e2-40ce-b848-628d354eb41c")]
            public virtual Ranorex.DivTag Ardbnz5BoxSearchCriteriaArfid30157300
            {
                get
                {
                    return _ardbnz5boxsearchcriteriaarfid30157300Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Ardbnz5BoxSearchCriteriaArfid30157300 item info.
            /// </summary>
            [RepositoryItemInfo("d9b8ae29-d7e2-40ce-b848-628d354eb41c")]
            public virtual RepoItemInfo Ardbnz5BoxSearchCriteriaArfid30157300Info
            {
                get
                {
                    return _ardbnz5boxsearchcriteriaarfid30157300Info;
                }
            }

            /// <summary>
            /// The UseBasicSearch item.
            /// </summary>
            [RepositoryItem("135e797f-b131-443e-a893-73e81471cd7c")]
            public virtual Ranorex.DivTag UseBasicSearch
            {
                get
                {
                    return _usebasicsearchInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UseBasicSearch item info.
            /// </summary>
            [RepositoryItemInfo("135e797f-b131-443e-a893-73e81471cd7c")]
            public virtual RepoItemInfo UseBasicSearchInfo
            {
                get
                {
                    return _usebasicsearchInfo;
                }
            }

            /// <summary>
            /// The Nobr item.
            /// </summary>
            [RepositoryItem("b68cc668-9f05-4883-bc06-4d5a264e1ebe")]
            public virtual Ranorex.WebElement Nobr
            {
                get
                {
                    return _nobrInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Nobr item info.
            /// </summary>
            [RepositoryItemInfo("b68cc668-9f05-4883-bc06-4d5a264e1ebe")]
            public virtual RepoItemInfo NobrInfo
            {
                get
                {
                    return _nobrInfo;
                }
            }

            /// <summary>
            /// The TestSummary item.
            /// </summary>
            [RepositoryItem("50ab632a-baf3-49a0-b360-471915c85fb8")]
            public virtual Ranorex.SpanTag TestSummary
            {
                get
                {
                    return _testsummaryInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TestSummary item info.
            /// </summary>
            [RepositoryItemInfo("50ab632a-baf3-49a0-b360-471915c85fb8")]
            public virtual RepoItemInfo TestSummaryInfo
            {
                get
                {
                    return _testsummaryInfo;
                }
            }

            /// <summary>
            /// The Relate item.
            /// </summary>
            [RepositoryItem("11905b33-bb6c-4560-b773-20f6ceb81f30")]
            public virtual Ranorex.DivTag Relate
            {
                get
                {
                    return _relateInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Relate item info.
            /// </summary>
            [RepositoryItemInfo("11905b33-bb6c-4560-b773-20f6ceb81f30")]
            public virtual RepoItemInfo RelateInfo
            {
                get
                {
                    return _relateInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("5fe3ab88-cf02-41e3-a874-a135184023aa")]
            public virtual Ranorex.Unknown NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("5fe3ab88-cf02-41e3-a874-a135184023aa")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }

            /// <summary>
            /// The INC0000000000681 item.
            /// </summary>
            [RepositoryItem("ebc48198-7b63-42f9-b750-6d0ae6f1477b")]
            public virtual Ranorex.SpanTag INC0000000000681
            {
                get
                {
                    return _inc0000000000681Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The INC0000000000681 item info.
            /// </summary>
            [RepositoryItemInfo("ebc48198-7b63-42f9-b750-6d0ae6f1477b")]
            public virtual RepoItemInfo INC0000000000681Info
            {
                get
                {
                    return _inc0000000000681Info;
                }
            }
        }

        /// <summary>
        /// The NewTabAppFolder folder.
        /// </summary>
        [RepositoryFolder("eb9433e0-0c90-4072-b5d2-7e4fb48a66f2")]
        public partial class NewTabAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new NewTab  folder.
            /// </summary>
            public NewTabAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewTab", "/dom[@domain='']", parentFolder, 30000, null, false, "eb9433e0-0c90-4072-b5d2-7e4fb48a66f2", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eb9433e0-0c90-4072-b5d2-7e4fb48a66f2")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eb9433e0-0c90-4072-b5d2-7e4fb48a66f2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The MozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("ca272b25-723b-4dd5-bf12-f017431bba8c")]
        public partial class MozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new MozillaFirefox  folder.
            /// </summary>
            public MozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MozillaFirefox", "/form[@title='Mozilla Firefox']", parentFolder, 30000, null, true, "ca272b25-723b-4dd5-bf12-f017431bba8c", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "d5c4abea-1f44-4a46-b76b-a9c9b7fea04b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ca272b25-723b-4dd5-bf12-f017431bba8c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ca272b25-723b-4dd5-bf12-f017431bba8c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("d5c4abea-1f44-4a46-b76b-a9c9b7fea04b")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("d5c4abea-1f44-4a46-b76b-a9c9b7fea04b")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The TortoiseGitAppFolder folder.
        /// </summary>
        [RepositoryFolder("c2973527-fabb-450d-9376-707097ab30d5")]
        public partial class TortoiseGitAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new TortoiseGit  folder.
            /// </summary>
            public TortoiseGitAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TortoiseGit", "/form[@title='TortoiseGit']", parentFolder, 30000, null, true, "c2973527-fabb-450d-9376-707097ab30d5", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "bad61efd-4823-4dc0-a042-45e7d51e29a8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c2973527-fabb-450d-9376-707097ab30d5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c2973527-fabb-450d-9376-707097ab30d5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("bad61efd-4823-4dc0-a042-45e7d51e29a8")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("bad61efd-4823-4dc0-a042-45e7d51e29a8")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The ChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("c1343d9b-4edd-4c9b-b7cb-b3ed53e09c71")]
        public partial class ChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pastectrlplusvInfo;

            /// <summary>
            /// Creates a new Chrome  folder.
            /// </summary>
            public ChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Chrome", "/form[@title='']", parentFolder, 30000, null, true, "c1343d9b-4edd-4c9b-b7cb-b3ed53e09c71", "")
            {
                _pastectrlplusvInfo = new RepoItemInfo(this, "PasteCtrlPlusV", "container[@accessiblename='']/menubar[@accessiblename='']//menuitem[@accessiblename='Paste Ctrl+V']", 30000, null, "02a8142a-5f05-4722-b0a2-65bede2ae30d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c1343d9b-4edd-4c9b-b7cb-b3ed53e09c71")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c1343d9b-4edd-4c9b-b7cb-b3ed53e09c71")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PasteCtrlPlusV item.
            /// </summary>
            [RepositoryItem("02a8142a-5f05-4722-b0a2-65bede2ae30d")]
            public virtual Ranorex.MenuItem PasteCtrlPlusV
            {
                get
                {
                    return _pastectrlplusvInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The PasteCtrlPlusV item info.
            /// </summary>
            [RepositoryItemInfo("02a8142a-5f05-4722-b0a2-65bede2ae30d")]
            public virtual RepoItemInfo PasteCtrlPlusVInfo
            {
                get
                {
                    return _pastectrlplusvInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
