///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SwissCom
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SwissComRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2987f7cf-f678-4558-8313-29bae9d1abe9")]
    public partial class SwissComRepository : RepoGenBaseFolder
    {
        static SwissComRepository instance = new SwissComRepository();

        /// <summary>
        /// Gets the singleton class instance representing the SwissComRepository element repository.
        /// </summary>
        [RepositoryFolder("2987f7cf-f678-4558-8313-29bae9d1abe9")]
        public static SwissComRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SwissComRepository() 
            : base("SwissComRepository", "/", null, 0, false, "2987f7cf-f678-4558-8313-29bae9d1abe9", ".\\RepositoryImages\\SwissComRepository2987f7cf.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2987f7cf-f678-4558-8313-29bae9d1abe9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SwissComRepositoryFolders
    {
    }
#pragma warning restore 0436
}
