///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SwissCom
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validateOriginIncidentDetails recording.
    /// </summary>
    [TestModule("d0511842-c028-4951-94c2-fca0b636da3e", ModuleType.Recording, 1)]
    public partial class validateOriginIncidentDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SwissComRepo repository.
        /// </summary>
        public static SwissComRepo repo = SwissComRepo.Instance;

        static validateOriginIncidentDetails instance = new validateOriginIncidentDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validateOriginIncidentDetails()
        {
            var_originStatus = "";
            var_statusReason2 = "";
            var_statusReason1 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validateOriginIncidentDetails Instance
        {
            get { return instance; }
        }

#region Variables

        string _var_originStatus;

        /// <summary>
        /// Gets or sets the value of variable var_originStatus.
        /// </summary>
        [TestVariable("8f290952-4dad-466b-b47a-be5bc914252d")]
        public string var_originStatus
        {
            get { return _var_originStatus; }
            set { _var_originStatus = value; }
        }

        string _var_statusReason2;

        /// <summary>
        /// Gets or sets the value of variable var_statusReason2.
        /// </summary>
        [TestVariable("8990c8a1-d01b-43a2-8d8a-6fd08d0d1a85")]
        public string var_statusReason2
        {
            get { return _var_statusReason2; }
            set { _var_statusReason2 = value; }
        }

        string _var_statusReason1;

        /// <summary>
        /// Gets or sets the value of variable var_statusReason1.
        /// </summary>
        [TestVariable("72f38bc9-e7d7-4592-9a30-723a8adc9b6c")]
        public string var_statusReason1
        {
            get { return _var_statusReason1; }
            set { _var_statusReason1 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$var_originStatus) on item 'IncidentForm.mn_status'.", repo.IncidentForm.mn_statusInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.IncidentForm.mn_statusInfo, "TagValue", var_originStatus);
            Delay.Milliseconds(0);
            
            Ranorex.AutomationHelpers.UserCodeCollections.ValidationLibrary.CompareValues(var_statusReason1, var_statusReason2);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
