///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SwissCom_Tests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The addImpactUrgency recording.
    /// </summary>
    [TestModule("7a5c759d-71b3-42d5-912a-fa495bc568a5", ModuleType.Recording, 1)]
    public partial class addImpactUrgency : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BMCtest333Repository repository.
        /// </summary>
        public static BMCtest333Repository repo = BMCtest333Repository.Instance;

        static addImpactUrgency instance = new addImpactUrgency();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public addImpactUrgency()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static addImpactUrgency Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentForm.mn_impact' at Center.", repo.IncidentForm.mn_impactInfo, new RecordItemIndex(0));
            repo.IncidentForm.mn_impact.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}' with focus on 'IncidentForm.mn_impact'.", repo.IncidentForm.mn_impactInfo, new RecordItemIndex(1));
            repo.IncidentForm.mn_impact.PressKeys("{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'IncidentForm.mn_impact'.", repo.IncidentForm.mn_impactInfo, new RecordItemIndex(2));
            repo.IncidentForm.mn_impact.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentForm.mn_urgency' at Center.", repo.IncidentForm.mn_urgencyInfo, new RecordItemIndex(3));
            repo.IncidentForm.mn_urgency.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}' with focus on 'IncidentForm.mn_urgency'.", repo.IncidentForm.mn_urgencyInfo, new RecordItemIndex(4));
            repo.IncidentForm.mn_urgency.PressKeys("{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'IncidentForm.mn_urgency'.", repo.IncidentForm.mn_urgencyInfo, new RecordItemIndex(5));
            repo.IncidentForm.mn_urgency.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
