///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SwissCom_Tests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createRelation recording.
    /// </summary>
    [TestModule("831dfd15-62a2-441a-bee6-4eb585ff5ffd", ModuleType.Recording, 1)]
    public partial class CreateRelation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BMCtest333Repository repository.
        /// </summary>
        public static BMCtest333Repository repo = BMCtest333Repository.Instance;

        static CreateRelation instance = new CreateRelation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateRelation()
        {
            var_originIncident = "INC000000000206";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateRelation Instance
        {
            get { return instance; }
        }

#region Variables

        string _var_originIncident;

        /// <summary>
        /// Gets or sets the value of variable var_originIncident.
        /// </summary>
        [TestVariable("41cad56b-604d-4bee-8165-ddd0b8af5792")]
        public string var_originIncident
        {
            get { return _var_originIncident; }
            set { _var_originIncident = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BMCRemedySearch.FormContainer.Relationships' at Center.", repo.BMCRemedySearch.FormContainer.RelationshipsInfo, new RecordItemIndex(0));
            repo.BMCRemedySearch.FormContainer.Relationships.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentForm.mn_searchRelationship' at Center.", repo.IncidentForm.mn_searchRelationshipInfo, new RecordItemIndex(1));
            repo.IncidentForm.mn_searchRelationship.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Return}' with focus on 'IncidentForm.mn_searchRelationship'.", repo.IncidentForm.mn_searchRelationshipInfo, new RecordItemIndex(2));
            repo.IncidentForm.mn_searchRelationship.PressKeys("{Down}{Down}{Down}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentForm.txt_searchValue' at Center.", repo.IncidentForm.txt_searchValueInfo, new RecordItemIndex(3));
            repo.IncidentForm.txt_searchValue.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'IncidentForm.txt_searchValue'.", repo.IncidentForm.txt_searchValueInfo, new RecordItemIndex(4));
            repo.IncidentForm.txt_searchValue.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentRelationshipSearch.btn_useAdvancedSearch' at Center.", repo.IncidentRelationshipSearch.btn_useAdvancedSearchInfo, new RecordItemIndex(5));
            repo.IncidentRelationshipSearch.btn_useAdvancedSearch.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentRelationshipSearch.txt_IncidentRelationship_IncidentID' at 69;12.", repo.IncidentRelationshipSearch.txt_IncidentRelationship_IncidentIDInfo, new RecordItemIndex(6));
            repo.IncidentRelationshipSearch.txt_IncidentRelationship_IncidentID.Click("69;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$var_originIncident' with focus on 'IncidentRelationshipSearch.txt_IncidentRelationship_IncidentID'.", repo.IncidentRelationshipSearch.txt_IncidentRelationship_IncidentIDInfo, new RecordItemIndex(7));
            repo.IncidentRelationshipSearch.txt_IncidentRelationship_IncidentID.PressKeys(var_originIncident);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentRelationshipSearch.txt_IncidentRelationship_searchValue' at Center.", repo.IncidentRelationshipSearch.txt_IncidentRelationship_searchValueInfo, new RecordItemIndex(8));
            repo.IncidentRelationshipSearch.txt_IncidentRelationship_searchValue.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentForm.mn_relationshipType' at Center.", repo.IncidentForm.mn_relationshipTypeInfo, new RecordItemIndex(9));
            repo.IncidentForm.mn_relationshipType.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Up}{Up}' with focus on 'IncidentForm.mn_relationshipType'.", repo.IncidentForm.mn_relationshipTypeInfo, new RecordItemIndex(10));
            repo.IncidentForm.mn_relationshipType.PressKeys("{Up}{Up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'IncidentForm.mn_relationshipType'.", repo.IncidentForm.mn_relationshipTypeInfo, new RecordItemIndex(11));
            repo.IncidentForm.mn_relationshipType.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentForm.btn_relateIncidentAssoc' at Center.", repo.IncidentForm.btn_relateIncidentAssocInfo, new RecordItemIndex(12));
            repo.IncidentForm.btn_relateIncidentAssoc.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(13));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(14));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
