///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BMCtest333
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording3 recording.
    /// </summary>
    [TestModule("2067493d-c196-482b-9e01-82d8483007d6", ModuleType.Recording, 1)]
    public partial class Recording3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BMCtest333Repository repository.
        /// </summary>
        public static BMCtest333Repository repo = BMCtest333Repository.Instance;

        static Recording3 instance = new Recording3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording3()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording3 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu down}' with focus on 'BMCRemedySearch'.", repo.BMCRemedySearch.SelfInfo, new RecordItemIndex(0));
            repo.BMCRemedySearch.Self.EnsureVisible();
            Keyboard.Press("{LMenu down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+Alt+Shift+F2' Press with focus on 'BMCRemedySearch'.", repo.BMCRemedySearch.SelfInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.BMCRemedySearch.Self);
            Keyboard.Press(System.Windows.Forms.Keys.F2 | System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Alt, 60, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu up}' with focus on 'BMCRemedySearch'.", repo.BMCRemedySearch.SelfInfo, new RecordItemIndex(2));
            repo.BMCRemedySearch.Self.EnsureVisible();
            Keyboard.Press("{LMenu up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'BMCRemedySearch.PageBodyPbChrome.ArdbnCustomerArfid303530000CharDf' at 5;53.", repo.BMCRemedySearch.PageBodyPbChrome.ArdbnCustomerArfid303530000CharDfInfo, new RecordItemIndex(3));
            repo.BMCRemedySearch.PageBodyPbChrome.ArdbnCustomerArfid303530000CharDf.DoubleClick("5;53");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentForm.txt_customer' at 35;7.", repo.IncidentForm.txt_customerInfo, new RecordItemIndex(4));
            repo.IncidentForm.txt_customer.Click("35;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tosho' with focus on 'IncidentForm.txt_customer'.", repo.IncidentForm.txt_customerInfo, new RecordItemIndex(5));
            repo.IncidentForm.txt_customer.PressKeys("tosho");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'IncidentForm.txt_customer'.", repo.IncidentForm.txt_customerInfo, new RecordItemIndex(6));
            repo.IncidentForm.txt_customer.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'BMCRemedySearch.PageBodyPbChrome.FieldSetTagPnl1' at 3;30.", repo.BMCRemedySearch.PageBodyPbChrome.FieldSetTagPnl1Info, new RecordItemIndex(7));
            repo.BMCRemedySearch.PageBodyPbChrome.FieldSetTagPnl1.MoveTo("3;30");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentForm.txt_detailedDescription' at 37;22.", repo.IncidentForm.txt_detailedDescriptionInfo, new RecordItemIndex(8));
            repo.IncidentForm.txt_detailedDescription.Click("37;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentForm.txt_detailedDescription' at 74;16.", repo.IncidentForm.txt_detailedDescriptionInfo, new RecordItemIndex(9));
            repo.IncidentForm.txt_detailedDescription.Click("74;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test notes' with focus on 'IncidentForm.txt_detailedDescription'.", repo.IncidentForm.txt_detailedDescriptionInfo, new RecordItemIndex(10));
            repo.IncidentForm.txt_detailedDescription.PressKeys("test notes");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentForm.txt_description' at 25;15.", repo.IncidentForm.txt_descriptionInfo, new RecordItemIndex(11));
            repo.IncidentForm.txt_description.Click("25;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test summary' with focus on 'IncidentForm.txt_description'.", repo.IncidentForm.txt_descriptionInfo, new RecordItemIndex(12));
            repo.IncidentForm.txt_description.PressKeys("test summary");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'BMCRemedySearch.PageBodyPbChrome.FieldSetTagPnl2' at 4;12.", repo.BMCRemedySearch.PageBodyPbChrome.FieldSetTagPnl2Info, new RecordItemIndex(13));
            repo.BMCRemedySearch.PageBodyPbChrome.FieldSetTagPnl2.MoveTo("4;12");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'IncidentForm.mn_impact' at 60;10.", repo.IncidentForm.mn_impactInfo, new RecordItemIndex(14));
            repo.IncidentForm.mn_impact.MoveTo("60;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IncidentForm.mn_impact' at 60;10.", repo.IncidentForm.mn_impactInfo, new RecordItemIndex(15));
            repo.IncidentForm.mn_impact.Click("60;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BMCRemedySearch.TdTag3ModerateLimited1' at 24;8.", repo.BMCRemedySearch.TdTag3ModerateLimited1Info, new RecordItemIndex(16));
            repo.BMCRemedySearch.TdTag3ModerateLimited1.Click("24;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'BMCRemedySearch.PageBodyPbChrome.Text1' at 50;17.", repo.BMCRemedySearch.PageBodyPbChrome.Text1Info, new RecordItemIndex(17));
            repo.BMCRemedySearch.PageBodyPbChrome.Text1.MoveTo("50;17");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BMCRemedySearch.PageBodyPbChrome.Text1' at 50;17.", repo.BMCRemedySearch.PageBodyPbChrome.Text1Info, new RecordItemIndex(18));
            repo.BMCRemedySearch.PageBodyPbChrome.Text1.Click("50;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BMCRemedySearch.TdTag3Medium1' at 38;8.", repo.BMCRemedySearch.TdTag3Medium1Info, new RecordItemIndex(19));
            repo.BMCRemedySearch.TdTag3Medium1.Click("38;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'BMCRemedySearch.PageBodyPbChrome.FieldSetTagPnl3' at 3;7.", repo.BMCRemedySearch.PageBodyPbChrome.FieldSetTagPnl3Info, new RecordItemIndex(20));
            repo.BMCRemedySearch.PageBodyPbChrome.FieldSetTagPnl3.MoveTo("3;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'service desk{Return}' with focus on 'BMCRemedySearch.PageBodyPbChrome.False2'.", repo.BMCRemedySearch.PageBodyPbChrome.False2Info, new RecordItemIndex(21));
            repo.BMCRemedySearch.PageBodyPbChrome.False2.PressKeys("service desk{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginPage.btn_logIn' at 9;2.", repo.LoginPage.btn_logInInfo, new RecordItemIndex(22));
            repo.LoginPage.btn_logIn.Click("9;2");
            Delay.Milliseconds(9090);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
